### ISSUE TITLE
Hola Alex me gusta tu tienda puedo ayudar en ajaxUnico.js

### ISSUE THREAD

**Issue by Zelechos** [TheAlexmen11/TiendaVirtual#2]
Hola @TheAlexmen11 creo que puedo ayudarte aplicando los últimos estándares de ES 6 y usando let en ves de var en tu código que te parece esto es lo que hice en tu archivo [ajaxUnico.js](https://github.com/TheAlexmen11/TiendaVirtual/blob/main/static/js/ajaxUnico.js)

```javascript
let READY_STATE_UNINITIALIZED=0;	//No se a inicializado
let READY_STATE_LOADING=1;			//Cargando
let READY_STATE_LOADED=2;			//Cargado
let READY_STATE_INTERACTIVE=3;		//Interactivo
let READY_STATE_COMPLETE=4;			//Completo
```

-

**Comment by TheAlexmen11** [comment]
hola Zelechos ,  si muchas gracias por tu ayuda lo modificare

**Comment by Zelechos** [comment]
dejame modificarlo a mi @TheAlexmen11  que dices??

**Comment by TheAlexmen11** [comment]
si  claro modifícalo

**Comment by Zelechos** [comment]
gracias gustoso de contribuir
